//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/11/2020 12:45:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FYPExchangeRateModel
{
    public partial class Transaction
    {

        public Transaction()
        {
            OnCreated();
        }

        public virtual int TransactionID
        {
            get;
            set;
        }

        public virtual int? FromCountryID
        {
            get;
            set;
        }
        [DataType(DataType.Currency)]
        public virtual decimal? FromCountryRate
        {
            get;
            set;
        }

        public virtual int? ToCountryID
        {
            get;
            set;
        }

        public virtual string CountryFrom
        {
            get;set;
        }

        public virtual string CountryTo
        {
            get; set;
        }
        [DataType(DataType.Currency)]
        public virtual decimal? ToCountryRate
        {
            get;
            set;
        }

        public virtual int? CustomerID
        {
            get;
            set;
        }

        public virtual string CustomerName
        {
            get;set;
        }

        public virtual string PaymentMethod
        {
            get;
            set;
        }
        [DataType(DataType.Currency)]
        public virtual decimal? InputMoneyAmount
        {
            get;
            set;
        }
        [DataType(DataType.Currency)]
        public virtual decimal? TotalCostAmount
        {
            get;
            set;
        }

        public virtual bool? IsConfirmed
        {
            get;
            set;
        }

        public virtual string Remarks
        {
            get;
            set;
        }

        public virtual bool? IsActive
        {
            get;
            set;
        }

        public virtual string IsActiveRemark
        {
            get;
            set;
        }

        public virtual int? CreatedBy
        {
            get;
            set;
        }

        public virtual System.DateTime? CreatedDate
        {
            get;
            set;
        }

        public virtual int? ModifiedBy
        {
            get;
            set;
        }

        public virtual System.DateTime? ModifiedDate
        {
            get;
            set;
        }

        public virtual Country Country_FromCountryID
        {
            get;
            set;
        }

        public virtual Country Country_ToCountryID
        {
            get;
            set;
        }

        public virtual User User
        {
            get;
            set;
        }

        public virtual IList<Enquiry> Enquiries
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
