//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/8/2020 12:09:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace FYPExchangeRateModel
{
    public partial class Country {

        public Country()
        {
            this.ExchangeRates_FromCountryID = new List<ExchangeRate>();
            this.ExchangeRates_ToCountryID = new List<ExchangeRate>();
            this.Transactions_FromCountryID = new List<Transaction>();
            this.Transactions_ToCountryID = new List<Transaction>();
            OnCreated();
        }

        public virtual int CountryID
        {
            get;
            set;
        }

        public virtual string CountryName
        {
            get;
            set;
        }

        public virtual decimal? CurrentCurrencyRate
        {
            get;
            set;
        }

        public virtual string Remarks
        {
            get;
            set;
        }

        public virtual bool? IsActive
        {
            get;
            set;
        }

        public virtual int? CreatedBy
        {
            get;
            set;
        }

        public virtual System.DateTime? CreatedDate
        {
            get;
            set;
        }

        public virtual int? ModifiedBy
        {
            get;
            set;
        }

        public virtual System.DateTime? ModifiedDate
        {
            get;
            set;
        }

        public virtual IList<ExchangeRate> ExchangeRates_FromCountryID
        {
            get;
            set;
        }

        public virtual IList<ExchangeRate> ExchangeRates_ToCountryID
        {
            get;
            set;
        }

        public virtual IList<Transaction> Transactions_FromCountryID
        {
            get;
            set;
        }

        public virtual IList<Transaction> Transactions_ToCountryID
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
